### ISSUE TITLE
Plotting points show large map and no points

### ISSUE THREAD

**Issue by csmu-cenr** [PacktPublishing/React-and-React-Native#16]
Suggest using zoom and some dummy locations based on the lat and log in the simulator.
![screen shot 2017-06-13 at 14 42 32](https://user-images.githubusercontent.com/742410/27066938-cd9abd8c-5046-11e7-8ded-e155df1199ea.png)

**Comment by adamboduch** [comment]
Hi @csmu-cenr.

I'm not sure that I understand this issue. Can you elaborate?

**Comment by csmu-cenr** [comment]
The simulator is using my location and just showing a large map of Australia. What the lat and log I could set in the simulator to show the results you intend to display?

**Comment by adamboduch** [comment]
Try `43.8384° N, 79.0868° W`

**Comment by csmu-cenr** [comment]
Hi Adam

I’m still getting the map of Australia for some reason.

Cheers


Keith John Hutchison
Software Development Director for
Referron, DashedUp.

0490 058 635

How you can track referrals via email <http://www.referron.com/how-can-i-refer-via-email>
Secret #4: Procrastination Can Be Overcome When You Figure Out How To Beat Your Future Self. - Kevin Kruse <https://greetings.balance-infosystems.com/#/insight_detail/57cccb851b27f43eaff7e1c4>

**Comment by csmu-cenr** [comment]
The zooming issue relates to setting latitudeDelta and longitudeDelta correctly.   

Here is a code extract that is setting the zoom correctly on my device and setting the position of a draggable marker where I am located. The rad2deg and deg2rad details can be found here https://stackoverflow.com/questions/30606827/set-the-bounds-of-a-mapview/39487945 

const earthRadiusInKM = 6371 ;
const radiusInKM = 1 ;
const aspectRatio = 1 ;

rad2deg (angle) {
  	return angle * 57.29577951308232 // angle / Math.PI * 180
}

deg2rad (angle) {
  	return angle * 0.017453292519943295 // (angle / 180) * Math.PI;


	componentWillMount() {

		
		const  setPosition = (pos) => {

	    // We need the "latitude" and the "longitude"
	    // in order to lookup the "address" from the
	    // Google maps API.
	    const {
	      coords: {
	        latitude,
	        longitude,
	      },
	    } = pos;
			
			var radiusInRad = radiusInKM / earthRadiusInKM ;
			var longitudeDelta = this.rad2deg(radiusInRad / Math.cos(this.deg2rad(latitude)));
      	  	var latitudeDelta = aspectRatio * this.rad2deg(radiusInRad);
			
			var region = {
				latitude: latitude,
				longitude: longitude,
				latitudeDelta: latitudeDelta,
				longitudeDelta: longitudeDelta,
			}
			this.data = this.data.set('region',region) ;
			
			var marker = {
				latitude: latitude,
				longitude: longitude,
				title: 'Help.',
				description: 'The person.',
			}
			this.data = this.data.set('marker', marker) ;
			
	    // Fetches data from the Google Maps API then sets
	    // the "address" state based on the response.
	    fetch(`${URL}${latitude},${longitude}`)
	      .then(resp => resp.json(), e => console.error(e))
	      .then(({
	        results: [
	          { formatted_address },
	        ],
	      }) => {
					
					this.setAddress( formatted_address ) ;
					this.startAlert() ;
	      });
	  } ;
	
    navigator.geolocation.getCurrentPosition(setPosition) ;
		
	}
}
