### ISSUE TITLE
resource-ids-in-routes in Chapter 9

### ISSUE THREAD

**Issue by invegat** [PacktPublishing/React-and-React-Native#17]
How do I run this project?   Do I start server.js separately?   The book doesn't' mention this file.

**Comment by adamboduch** [comment]
Hi @invegat,
you should just be able to run `webpack-dev-server --hot`.

**Comment by invegat** [comment]
No, I left the book and went to another and learned some more about node and react.  I should have realized from this book the way to run this project is "node server.js", then navigate to http://localhost:8080/webpack-dev-server/users/0 or /users/1
