### ISSUE TITLE
Chapter 9 "url-and-query-parameters"

### ISSUE THREAD

**Issue by invegat** [PacktPublishing/React-and-React-Native#18]
Couldn't get it to work. Did a 'yarn upgrade -L' at the root
Changed App.js query lines to
`const query = 'From Query';`
`<p><Link to={{ pathname: '/echo', search: `?value=${query}` }}>Echo query</Link></p>`
Changed Echo.js to
`import React from 'react';
import { parse } from 'query-string';

// Simple component that expects either an "echo"
// URL segment parameter, or an "echo" query parameter.
export default ({
  params,
  location: {
    search,
  },
}) => (
  <div>
    <h1>{params.echo || parse(search).value}</h1>
  </div>
  );`
That worked

**Comment by adamboduch** [comment]
@invegat So you have it figured out?

**Comment by invegat** [comment]
Yes, instead the 'query' attribute is obsolete and replace by the 'search' attribute, to resolve the key/value entries use "import { parse } from 'query-string';"
