### ISSUE TITLE
error for Chapter 13 MyProject.xcodeproj

### ISSUE THREAD

**Issue by invegat** [PacktPublishing/React-and-React-Native#20]
This generates a not found error: <React/CTBundleURLProvider.h>

**Comment by adamboduch** [comment]
@invegat What did you do to trigger that error?

**Comment by invegat** [comment]
Once I fixed https://github.com/yarnpkg/yarn/issues/648 and was able to do your steps https://github.com/PacktPublishing/React-and-React-Native#building-react-native-projects it worked, thanks.
