### ISSUE TITLE
Error when npm install, express-graphql@0.6.11 requires a peer of graphql@^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by yuliantosb** [PacktPublishing/React-and-React-Native#24]
Hello Mr. Boduch, I'm still a beginner and I just clone the repository and follow the instructor, but I got an error, the error said

 ```
WARN express-graphql@0.6.11 requires a peer of graphql@^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 116 packages in 10.36s

```

I have no idea what should I do then, my nodejs version is 8.9.1 and npm version is 5.5.1
thanks

**Comment by adamboduch** [comment]
@yuliantosb Try `npm install graphql@^0.11.0`. You should be good to go afterward.

**Comment by yuliantosb** [comment]
I just skipped that, and run without graphql and it's works fine, I'm still on Capter02 anyway, ok thanks for your answer mr. Boduch
