### ISSUE TITLE
is +Date documented anywhere?

### ISSUE THREAD

**Issue by invegat** [PacktPublishing/React-and-React-Native#8]
From console.log
state.modified: Tue Jun 06 2017 14:14:52 GMT-0400 (Eastern Daylight Time)
+state.modified: 1496772892489
I see that the + symbol converted the Date to ticks, is that documented anywhere?

**Comment by adamboduch** [comment]
Hi @invegat 
I assume you're referring to the _using meta data_ example from chapter 6? The `+` operator will cast the date object to a number (the timestamp).

It's the same as calling `getTime()`:
```js
const myDate = new Date();
+myDate;
// 1496847145992
myDate.getTime();
// 1496847145992
```
