### ISSUE TITLE
Issue with LazyListLoading example.

### ISSUE THREAD

**Issue by csmu-cenr** [PacktPublishing/React-and-React-Native#9]
Unable to resolve module http from /source/React-and-React-Native/Chapter16/LazyListLoading/node_modules/node-fetch/index.js: Module does not exist in the module map or in these directories:
  /source/React-and-React-Native/Chapter16/LazyListLoading/node_modules
,   /source/React-and-React-Native/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

RCTFatal
-[RCTBatchedBridge stopLoadingWithError:]
__25-[RCTBatchedBridge start]_block_invoke_2
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by adamboduch** [comment]
Hi @csmu-cenr.

I was able to reproduce your issue, but there's no easy answer I'm afraid. It'll require some investigation and I'll look into it as soon as I get the chance.

**Comment by csmu-cenr** [comment]
Thanks Adam

Cheers

Keith

**Comment by adamboduch** [comment]
Fixed in 681dd2d7

**Comment by csmu-cenr** [comment]
Thanks Adam!
